# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-06-09 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_photo', models.CharField(max_length=264, unique=True)),
                ('serviceName', models.CharField(max_length=264, unique=True)),
                ('serviceDescription', models.TextField(max_length=1000)),
                ('serviceStatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('FileName', models.CharField(max_length=264, unique=True)),
                ('ContentOne', models.CharField(max_length=200)),
                ('ContentTwo', models.TextField(max_length=1000)),
                ('SliderNo', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=70, unique=True)),
                ('twitter', models.CharField(max_length=70, unique=True)),
                ('instagram', models.CharField(max_length=70, unique=True)),
                ('photo', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
