# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-06-09 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNo', models.CharField(max_length=40, unique=True)),
                ('emailAddress', models.CharField(max_length=70, unique=True)),
                ('officeAvailability', models.CharField(max_length=50)),
                ('websiteName', models.CharField(max_length=100, unique=True)),
                ('GoogleMap', models.CharField(max_length=1000)),
            ],
        ),
    ]
