# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-06-11 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50, unique=True)),
                ('content', models.CharField(max_length=120)),
                ('para', models.TextField()),
                ('checklist1', models.CharField(max_length=50)),
                ('checklist2', models.CharField(max_length=50)),
                ('checklist3', models.CharField(max_length=50)),
                ('checklist4', models.CharField(max_length=50)),
                ('checklist5', models.CharField(max_length=50)),
                ('checklist6', models.CharField(max_length=50)),
                ('checklist7', models.CharField(max_length=50)),
                ('checklist8', models.CharField(max_length=50)),
            ],
        ),
    ]
