# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-06-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_setting',
            name='companyName',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='contact_setting',
            name='content',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contact_setting',
            name='cright_company',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contact_setting',
            name='facebook',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='contact_setting',
            name='information_cont',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contact_setting',
            name='instagram',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='contact_setting',
            name='tel_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact_setting',
            name='twitter',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='contact_setting',
            name='working_hours',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
