# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-06-11 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200611_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_setting',
            name='GoogleMap',
            field=models.TextField(null=True),
        ),
    ]
