# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-06-13 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200611_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='FileName',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
