# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-06-13 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200613_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='myImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='FileName',
            field=models.CharField(default=1, max_length=264, unique=True),
            preserve_default=False,
        ),
    ]
