# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-15 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200613_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='FileName',
            field=models.CharField(max_length=264),
        ),
    ]
