# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-15 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200615_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(max_length=264),
        ),
    ]
